import fs from 'fs';
import path from 'path';

const controllers = {
  'authController.js': "import User from '../models/User.js';\nimport jwt from 'jsonwebtoken';\nimport bcrypt from 'bcryptjs';\n\nconst signToken = (_id) => jwt.sign({ _id }, process.env.SECRET || 'trackmate_secret', { expiresIn: '7d' });\n\nexport const login = async (req, res) => {\n  const { username, password, role } = req.body;\n  try {\n    let user = await User.findOne({ username }).populate('assignedBusId');\n    if (!user) {\n      const salt = await bcrypt.genSalt(10);\n      const hashedPassword = await bcrypt.hash(password || 'dummy', salt);\n      user = await User.create({ username, password: hashedPassword, name: username, role: role || 'student' });\n    } else {\n      const match = await bcrypt.compare(password || 'dummy', user.password);\n      if (!match) return res.status(400).json({ error: 'Incorrect password' });\n    }\n    const token = signToken(user._id);\n    res.status(200).json({ username, token, user });\n  } catch (error) {\n    res.status(400).json({ error: error.message });\n  }\n};\n\nexport const getMe = async (req, res) => {\n  try {\n    const user = await User.findById(req.user._id).select('-password');\n    res.status(200).json(user);\n  } catch (error) {\n    res.status(400).json({ error: error.message });\n  }\n};",
  'busController.js': "import Bus from '../models/Bus.js';\nexport const getBuses = async (req, res) => { try { res.status(200).json(await Bus.find().populate('driverId').populate('routeId')); } catch (e) { res.status(400).json({error:e.message}); } };\nexport const createBus = async (req, res) => { try { res.status(201).json(await Bus.create(req.body)); } catch (e) { res.status(400).json({error:e.message}); } };",
  'routeController.js': "import Route from '../models/Route.js';\nexport const getRoutes = async (req, res) => { try { res.status(200).json(await Route.find().populate('stops')); } catch (e) { res.status(400).json({error:e.message}); } };\nexport const createRoute = async (req, res) => { try { res.status(201).json(await Route.create(req.body)); } catch (e) { res.status(400).json({error:e.message}); } };",
  'stopController.js': "import Stop from '../models/Stop.js';\nexport const getStops = async (req, res) => { try { res.status(200).json(await Stop.find().sort({sequence:1})); } catch (e) { res.status(400).json({error:e.message}); } };\nexport const createStop = async (req, res) => { try { res.status(201).json(await Stop.create(req.body)); } catch (e) { res.status(400).json({error:e.message}); } };",
  'tripController.js': "import Trip from '../models/Trip.js';\nimport Bus from '../models/Bus.js';\nexport const startTrip = async (req, res) => { try { const { busId } = req.body; let trip = await Trip.findOne({ busId, status: 'active' }); if (!trip) { trip = await Trip.create({ busId, driverId: req.user._id }); } await trip.populate(['busId', 'routeId']); res.status(200).json(trip); } catch (e) { res.status(400).json({error:e.message}); } };\nexport const getActiveTrip = async (req, res) => { try { const trip = await Trip.findOne({ driverId: req.user._id, status: 'active' }).populate(['busId', 'routeId']); res.status(200).json(trip || {}); } catch (e) { res.status(400).json({error:e.message}); } };\nexport const endTrip = async (req, res) => { try { const tripId = req.params.id || req.body.tripId; const trip = await Trip.findByIdAndUpdate(tripId, { status: 'ended', endedAt: Date.now() }, { new: true }); res.status(200).json(trip); } catch (e) { res.status(400).json({error:e.message}); } };",
  'studentController.js': "import Trip from '../models/Trip.js';\nexport const getStudentTrip = async (req, res) => { try { const trip = await Trip.findOne({ status: 'active' }).populate('busId routeId driverId'); res.status(200).json(trip || null); } catch (e) { res.status(400).json({error:e.message}); } };\nexport const getEta = async (req, res) => { res.status(200).json({ etaMinutes: 5 }); };",
  'adminController.js': "import User from '../models/User.js';\nimport bcrypt from 'bcryptjs';\nexport const getStudents = async (req,res) => { try { res.status(200).json(await User.find({role: 'student'}).populate(['assignedBusId','assignedStopId','assignedRouteId'])); } catch(e){ res.status(400).json({error:e.message}); } };\nexport const getDrivers = async (req,res) => { try { res.status(200).json(await User.find({role: 'driver'}).populate('assignedBusId')); } catch(e){ res.status(400).json({error:e.message}); } };\nexport const createUser = async (req,res) => { try { const data={...req.body}; const salt=await bcrypt.genSalt(10); data.password=await bcrypt.hash(req.body.password||'password123', salt); res.status(201).json(await User.create(data)); } catch(e){ res.status(400).json({error:e.message}); } };"
};

const routes = {
  'auth.js': "import express from 'express';\nimport { login, getMe } from '../controllers/authController.js';\nimport { requireAuth } from '../middleware/auth.js';\nconst router = express.Router();\nrouter.post('/login', login);\nrouter.get('/me', requireAuth, getMe);\nexport default router;",
  'buses.js': "import express from 'express';\nimport { getBuses, createBus } from '../controllers/busController.js';\nconst router = express.Router();\nrouter.get('/', getBuses);\nrouter.post('/', createBus);\nexport default router;",
  'routes.js': "import express from 'express';\nimport { getRoutes, createRoute } from '../controllers/routeController.js';\nconst router = express.Router();\nrouter.get('/', getRoutes);\nrouter.post('/', createRoute);\nexport default router;",
  'stops.js': "import express from 'express';\nimport { getStops, createStop } from '../controllers/stopController.js';\nconst router = express.Router();\nrouter.get('/', getStops);\nrouter.post('/', createStop);\nexport default router;",
  'trips.js': "import express from 'express';\nimport { startTrip, getActiveTrip, endTrip } from '../controllers/tripController.js';\nimport { requireAuth } from '../middleware/auth.js';\nconst router = express.Router();\nrouter.use(requireAuth);\nrouter.post('/start', startTrip);\nrouter.get('/active', getActiveTrip);\nrouter.post('/end', endTrip);\nrouter.post('/:id/end', endTrip);\nexport default router;",
  'students.js': "import express from 'express';\nimport { getStudentTrip, getEta } from '../controllers/studentController.js';\nimport { requireAuth } from '../middleware/auth.js';\nconst router = express.Router();\nrouter.use(requireAuth);\nrouter.get('/trip', getStudentTrip);\nrouter.get('/eta', getEta);\nexport default router;",
  'admin.js': "import express from 'express';\nimport { getStudents, getDrivers, createUser } from '../controllers/adminController.js';\nimport { requireAuth } from '../middleware/auth.js';\nconst router = express.Router();\nrouter.use(requireAuth);\nrouter.get('/students', getStudents);\nrouter.post('/students', createUser);\nrouter.get('/drivers', getDrivers);\nrouter.post('/drivers', createUser);\nexport default router;"
};

for (const [filename, content] of Object.entries(controllers)) { fs.writeFileSync(path.join('controllers', filename), content); }
for (const [filename, content] of Object.entries(routes)) { fs.writeFileSync(path.join('routes', filename), content); }

const socketsJs = "import Bus from '../models/Bus.js';\nexport const setupSockets = (io) => {\n  io.on('connection', (socket) => {\n    console.log('🔗 Client connected:', socket.id);\n    socket.on('driver:location_update', async (payload) => {\n      if (payload.busId) {\n        await Bus.findByIdAndUpdate(payload.busId, {\n          lastKnownLocation: { lat: payload.lat, lng: payload.lng, updatedAt: Date.now() }\n        });\n        if (payload.tripId) {\n          io.to('trip_'+payload.tripId).emit('trip:location_update', payload);\n        }\n      }\n    });\n    socket.on('student:subscribe', (payload) => {\n      if (payload.tripId) socket.join('trip_'+payload.tripId);\n    });\n    socket.on('disconnect', () => {});\n  });\n};\n";
fs.writeFileSync(path.join('utils', 'sockets.js'), socketsJs);
console.log('Controllers, Routes, and Sockets scaffolded successfully.');
